"""
startup_node.py

Defines StartupNode, a synthetic node representing a startup idea generated by the system.
It contains optional metadata describing the business model, pain point, and societal impact.
"""

from .node import Node
import numpy as np

class StartupNode(Node):
    def __init__(self, node_id, name, business_model, pain_point, impact):
        """
        Initialize a startup idea node.

        Args:
            node_id (str): Unique identifier (e.g., 'STARTUP_ID').
            name (str): Name or short label of the startup.
            business_model (str): Description of the proposed business model (optional).
            pain_point (str): Societal/market problem addressed by the idea (optional).
            impact (str): Expected SDG-related impact (optional).
        """
        super().__init__(node_id)
        self.name = name
        self.business_model = business_model
        self.pain_point = pain_point
        self.impact = impact
